_target_: src.models.cxr_module.CXRModel

lr: 0.001
weight_decay: 0.0005

model: "chexpert"
pretrained: True
drop_rate: 0
optimizer: "Adam"
momentum: 0
eps: 1e-08
alpha: 0.99
dampening: 0
betas: [0.9, 0.999]
centered: False
nesterov: False
amsgrad: False