defaults:
  - default.yaml
watch_model:
  _target_: src.callbacks.wandb_callbacks.WatchModel
  log: "all"
  log_freq: 100
log_f1_precision_recall_heatmap:
  _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmap
log_confusion_matrix:
  _target_: src.callbacks.wandb_callbacks.LogConfusionMatrix
log_image_predictions:
  _target_: src.callbacks.wandb_callbacks.LogImagePredictions
  num_samples: 8