# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: cxr.yaml # choose the datamodule for evaluation
  - model: cxr.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/pneumonia/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: logs/experiments/runs/chexpert_dense_net/2022-05-17_16-10-07/checkpoints/last.ckpt
